version: '3.1'

services:
    api:
        build: .
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: 123
        volumes:
            - db-volume:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    db-volume: