version: "3"

services:
    web:
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27018:27017"
        

