version: "3"

services:
    web:
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        image: mongo
        restart: always
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_DATABASE: "mydatabase"
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "123"
        

