version: "3"

services:
    web:
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        

